### PR TITLE
authenticator annotation exemple

### PR DESCRIPTION
**Pull request by jeanouii**

### CODE REVIEW

**Comment by arjantijms** [comment]
What's an "Authenticator" here?

We had this term in the vote related to https://java.net/jira/browse/JAVAEE_SECURITY_SPEC-1

It proved to be a difficult term as some systems use it to mean "authentication mechanism" while others use it for "identity store". It's therefore a bit ambiguous.

**Comment by keilw** [comment]
Any idea what to do with this PR? It seems changes in recent time made it hard to merge.

**Comment by arjantijms** [comment]
I'm not sure either. The main thing in this gist seemed to be adding an "authenticator", which was defined as:

```
public @interface Authenticator {
    // The authenticator class name
    String value();
}
```

As I mentioned above, authenticator in the past was used for both "authentication mechanism" and "identity store". The example code is not complete enough to be really sure. It's only used here:

```
@Authenticator("javax.security.authenticator.OpenIDConnect")
@WebServlet("/SimpleServlet")
@ServletSecurity(
    @HttpConstraint(rolesAllowed = {"manager"})
)
public class MyServlet extends HttpServlet {
```

As OpenID is normally about the interaction with the user, my guess is that this is supposed to be the authentication mechanism. I.e. via this annotation the application indicates which SAM is going to be used.

**Comment by arjantijms** [comment]
p.s. in one of the other proposals there's also an annotation called "Authenticator", see https://github.com/javaee-security-spec/javaee-security-proposals/blob/master/user-and-role-service/src/main/java/javax/security/auth/Authenticator.java

Currently investigating what that was exactly functionally meant to accomplish and see if it can be renamed.

**Comment by keilw** [comment]
After the structure change, this PR is likely irrelevant or merging it would be extremely difficult. WDYT?

**Comment by arjantijms** [comment]
I suggest closing it and asking Jean-Louis to resubmit it, perhaps after some discussion of what an "authenticator" was meant to be? @jeanouii what do you think?

**Comment by arjantijms** [comment]
p.s. as Jean-Louis is from Tomitribe, and TomEE uses the term "authenticator" for what we called "authentication mechanism" here (see e.g. http://www.tomitribe.com/blog/2014/09/tomee-security-episode-1-apache-tomcat-and-apache-tomee-security-under-the-covers), my guess is that the authenticator from the PR was intended to be the annotation via which an application defines the SAM to be used.

**Comment by keilw** [comment]
This no longer makes sense and would cause conflicts after massive refactoring.

**Pull request closed without merging**
