### PR TITLE
Proposal for LDAP IdentityStore which searches the DN of the caller.

### PR DESCRIPTION
**Pull request by rdebusscher**
Arjan/Experts

A version where the LDAP identity store also can authenticate by searching the Caller in the LDAP tree in case there are multiple organizational units.

### CODE REVIEW

**Comment by arjantijms** [comment]
Looks great, but the Soteria repo had been moved to https://github.com/javaee-security-spec/soteria

This was just a left-over proposal. As Werner mentioned, to avoid confusion we'd better remove this duplicate copy.

**Comment by rdebusscher** [comment]
I'll prepare the PR this weekend then.

thx

**Comment by arjantijms** [comment]
Ok, thanks! Should be easy I think. ldap2/\* files can directly be copied and LdapIdentityStoreDefinition.java and LdapIdentityStore.java can likely just be copied over the versions in https://github.com/javaee-security-spec/soteria

**Comment by keilw** [comment]
"copied over" sounds a bit messy. At the moment we have an "unholy trinity" of API drafts between here, the "official" (but practically dead/empty) "api" repo and a fork/copy under "soteria". While this was meant to be a "sandbox" very soon, see JSR 354 it should go away or just serve new, possibly incompatible experiments. The "embedded" API in Soteria is also sub-optimal, and it can't go on like this forever, but as a first step if we really have to, it could be acceptable. The process (and EC) demands we get things done and produce an EDR relatively soon.

**Comment by arjantijms** [comment]
I agree, but "copy over" or "redo the changes for the right repo".

The trinity or actually 4-in-one  is indeed a little weird, in chronological order of commits it would be:
1. **Proposals repository** - https://github.com/javaee-security-spec/javaee-security-proposals
2. **Upstream working repository API + Impl** - https://github.com/javaee-security-spec/soteria
3. **The Truth API** - https://java.net/projects/javaee-security-spec/sources/spec-api/show
4. **Mirror of The Truth API** - https://github.com/javaee-security-spec/spec-api

The Truth is however empty as you mentioned. To the best of my knowledge, no one from the EG has access to it. It's an Oracle requirement, so at some point we should deal with it.

But practically speaking, for now we have:
1. **Proposals repository** - https://github.com/javaee-security-spec/javaee-security-proposals
2. **Upstream working repository API + Impl** - https://github.com/javaee-security-spec/soteria

The categorized proposals in {authentication, authorization and overall} should be kept I think, even when they basically move to Soteria, but {soteria-edr1, apps} should be removed from there. I should have done that before, so my apologies for not doing doing that earlier.

> The "embedded" API in Soteria is also sub-optimal, and it can't go on like this forever, but as a first step if we really have to, it could be acceptable

Indeed, this is not optimal. I put it there so we at least have _something_, but before long we have to move it.

Another non-optimal thing is the snapshot using the org.omnifaces group id. (see http://arjan-tijms.omnifaces.org/p/whats-new-in-java-ee-security-api-10.html).

**Comment by rdebusscher** [comment]
PR to 'other' gitHub repository is sent.

regards
Rudy

**Pull request merged**
