### PR TITLE
Code example for Permissions concept #11

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Comment by keilw** [comment]
I trust  

> From Apache Shiro / Octopus 

does not suggest any of this was a blunt 1:1 copy from these projects?;-)

**Comment by rdebusscher** [comment]
Werner,

It is not a plain copy and paste, but of course major code parts are
copied. And the concepts are taken from those frameworks (as I happen to
have written one of them ;-) )

I thought it was convenient in the light of issue 14 to discuss it based on
some code.

And of course, it is just a proposal.

Rudy

**Comment by keilw** [comment]
As a comment in a proposal it seems fair, just keep in mind, if we end up contributing one or the other into a "javax.security.*" package space, something like "From Apache" doesn't look so good;-)

**Comment by rdebusscher** [comment]
Ok, I can understand that.

But I hope that this doesn't mean that we aren't allowed to look for good
ideas which are available in some of the Apache projects.

**Comment by keilw** [comment]
I don't think so, both Apache and ICU have inspired the JDK and Java EE in many areas;-)

**Pull request merged**
